import = ["/home/dev/.alacritty-themes/one_dark.yaml"]

[colors]
draw_bold_text_with_bright_colors = false

[env]
TERM = "alacritty"

[font]
size = 12.0

[font.bold]
family = "FantasqueSansM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FantasqueSansM Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FantasqueSansM Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FantasqueSansM Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[scrolling]
history = 5000

[window]
dynamic_padding = false
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
